In [1]:
import numpy as np

1. Write a NumPy program to create an array of 10 zeros, array of 10 ones, and 
array of 10 fives.

In [47]:
zeros_array = np.zeros(10)

ones_array = np.ones(10)

fives_array = np.full(10, 5)

zeros_array
ones_array
fives_array


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

2. Write a NumPy program to create an array of all even integers from 30 to 70. 

In [48]:
even_numbers = np.arange(30, 70, 2)
even_numbers

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

3. Write a NumPy program to create an array of given shape (5,6) and integer 
type, filled with zeros. 

In [ ]:
zeros_array = np.zeros((5, 6), dtype=int)
zeros_array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

4. Create a 10x10 array with random values and find the minimum and 
maximum values.

In [20]:
random_array = np.random.rand(10,10)
random_array

array([[0.73566946, 0.58756348, 0.04087432, 0.49631818, 0.75446329,
        0.0385484 , 0.75249596, 0.03776084, 0.8670192 , 0.5881418 ],
       [0.68876946, 0.16135603, 0.05108016, 0.65385428, 0.30298083,
        0.03390966, 0.76384919, 0.63264212, 0.7225009 , 0.54397541],
       [0.68023266, 0.38746579, 0.28109315, 0.67922525, 0.98082184,
        0.50632445, 0.03984533, 0.03325712, 0.43336645, 0.57254953],
       [0.87080436, 0.29532435, 0.85563354, 0.68329381, 0.94695673,
        0.6948923 , 0.8640208 , 0.65674472, 0.21253141, 0.61398357],
       [0.05953925, 0.17208502, 0.12070731, 0.37884403, 0.64752507,
        0.45504929, 0.8262945 , 0.93711998, 0.34430482, 0.15977015],
       [0.8557111 , 0.48597726, 0.57256574, 0.32811669, 0.34852482,
        0.31332636, 0.58028732, 0.35711952, 0.95199367, 0.60447819],
       [0.55911328, 0.95499905, 0.73241405, 0.68211974, 0.57929593,
        0.75913024, 0.79591878, 0.09433553, 0.91537873, 0.57879161],
       [0.57629055, 0.20807756, 0.1160946

In [21]:
random_array.max() ,random_array.min()

(np.float64(0.9812608114876102), np.float64(0.0016704905828659466))

5. Write a NumPy program to create a 3x3 array with values ranging from 2 to 10. 

In [ ]:
arr = np.arange(2, 11).reshape(3, 3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

6. Write a NumPy program to create an array of size = 20 using arrange, then 
extract all numbers from a given array greater than 15. 

In [ ]:
arr = np.arange(20)

result = arr[arr > 15]

result

array([16, 17, 18, 19])

7. Write a NumPy program to combine the two 2-dimensional arrays using 
hstack and vstack. 
Array 1: [[0, 1, 3], [5, 7, 9]] 
Array 2: [[0, 2, 4], [6, 8, 10]]

In [38]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])

In [39]:
h_result = np.hstack((arr1, arr2))
h_result

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [40]:
v_result = np.vstack((arr1, arr2))
v_result

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

8. Write a NumPy program to create ones array of size 10 and change the 6th 
element to 11. 

In [42]:
arr = np.ones(10, dtype=int)
arr[5] = 11
arr

array([ 1,  1,  1,  1,  1, 11,  1,  1,  1,  1])

9. Write a NumPy program to append a value to the end of an array. 


In [33]:
arr = np.array([1, 2, 3, 4, 5])

new_arr = np.append(arr, 6)

new_arr

array([1, 2, 3, 4, 5, 6])

10. Write a NumPy program to reverse an array [using two different methods]. 


slicing

In [44]:
arr = np.array([1, 2, 3, 4, 5])

reversed_arr1 = arr[::-1]
reversed_arr1

array([5, 4, 3, 2, 1])

flip

In [45]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr2 = np.flip(arr)
reversed_arr2


array([5, 4, 3, 2, 1])

Reverse

In [ ]:
arr = [1, 2, 3, 4, 5]
arr.reverse()
arr

[5, 4, 3, 2, 1]